import './globals.css'
import '../styles/map.css'

import type { Metadata } from 'next'

import AuthProvider from '../components/organisms/AuthProvider'
import { ThemeProvider } from '../components/organisms/theme-provider'
import { Container } from '../components/atoms/container'
import { Header } from '../components/molecules/Header'
import { Toaster } from '../components/atoms/toaster'
import { cn } from '../util'
import { fontSans } from '../util/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            <Container>{children}</Container>
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
